name = "mixtape"
compatibility_date = "2025-01-01"
main = "worker.js"

[assets]
directory = "."

[[d1_databases]]
binding = "DB"
database_name = "mixtape-auth"
database_id = "7d8e4903-2447-40cc-b1b9-279ef071b5f1"

[[r2_buckets]]
binding = "AUDIO_BUCKET"
bucket_name = "mixtape-audio"
